name: Deploy DevOps Project

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 15.168.189.56
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd devops-project/HN_KS23B_HaHuyenTrang_002
  git pull
  docker-compose down
  docker-compose build --no-cache
  docker-compose up -d